package com.racket.consumer.exception

class RetryCallRequiredException: RuntimeException() {
}